//*********************************************************************************************************************
//* File Name:      pch.h
//* Description:    Precompiled header file
//*                 Files listed below are compiled only once, improving build performance for future builds.
//*                 This also affects IntelliSense performance, including code completion and many code browsing features.
//*                 However, files listed here are ALL re-compiled if any one of them is updated between builds.
//*                 Do not add files here that you will be updating frequently as this negates the performance advantage.
//*
//* Copyright (C) 2022 Mike Pullen. All Rights Reserved.
//* Confidential and Proprietary
//*
//* Revision History: 
//=====================================================================================================================
//* 2022/09/10 - Mike Pullen - Original implementation.
//* 2022/10/30 - Mike Pullen - Recreated under VS2022 and added ARM64 support.
//*********************************************************************************************************************
#pragma once

// add headers that you want to pre-compile here
#include "framework.h"

// Disable the warnings generated by 3rd party header
#pragma warning(disable : 26495)
#include "rng.h"
#pragma warning(default : 26495)